lsi: false
safe: true
source: [content/]
incremental: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Webb.fyi
tagline: Learning things the hard way so you don't have to ;)
# description:
show_downloads: false
# google_analytics:
