lsi: false
safe: true
github:
  is_project_page: false
incremental: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

remote_theme: pages-themes/midnight@v0.2.0
show_downloads: false
# google_analytics:

relative_links:
  enabled: true
  collections: true

title: Webb.fyi
tagline: Learning things the hard way so you don't have to ;)
# description:
